### PR TITLE
Delete Audit Report -  Betoken [20.05.2019].pdf

### PR DESCRIPTION
**Pull request by tuanggo**

### CODE REVIEW

**Comment by fabiohild** [comment]
Hey @tuanggo , how are you? 

Why do you want to delete the audit report? 

Thanks!

**Comment by fabiohild** [comment]
Hey @tuanggo, noticed you reopened the PR, we have never deleted a published report before, why exactly do you want to remove this one?

**Comment by BigbossHvb** [comment]
Yes

**Comment by fabiohild** [comment]
No reason specified for removing it. closing the issue.

**Pull request closed without merging**
